-- +migrate Up
CREATE table feed (
  id INTEGER PRIMARY KEY,
  name text NOT NULL,
  url text NOT NULL UNIQUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  lastSyncedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- +migrate Down
DROP TABLE feed;
